version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    volumes:
      - ~/.cache/tari/tmp/:/var/log
      - ./promtail.config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana
    user: "${UID:-root}:${GID:-root}"
    volumes:
      - ./grafana/defaults.ini:/usr/share/grafana/conf/defaults.ini
      - ./grafana/sources_provision.yml:/etc/grafana/provisioning/datasources/all.yml # for some reason does not work if volumed into /usr/share/grafana/conf/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
