# Runs daily
name: Launchpad v2 NPM audit
on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  launchpad_v2_audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: "launchpad_such_wow"
      - name: check environment
        run: |
          node -v
          npm -v
          yarn -v
      - name: npm audit launchpad_v2
        run: |
          cd applications/launchpad_v2
          yarn audit
